# Site settings
title: Jan Czizikow
description: Jan Czizikow - a senior BBA student with passion for digital marketing based in Shanghai, China. Let's work together - email or view CV to get in touch.
baseurl: ""
url: "https://www.janczizikow.com"

# Social
socialimg: /img/social.jpg # 1200 x 630 pixels
facebook: johnny.czizikow
twitter: jan_czizikow
linkedin: janczizikow
behance: janczizikow
github: janczizikow
googleplus: 106682453870996888295
instagram: shanlongjj

# Contact
phone: "(+86) 131-6700-7112"
email: "jan.czizikow@gmail.com"

#Others
markdown: kramdown
highlighter: rouge # or pygments or null
exclude: [README.md, assets/css/pages, "node_modules", "bower_components", Gemfile, "package.json", "bower.json", vendor]
include: ['_pages']
permalink: /:title/
# Gems
gems:
  - jekyll-paginate
  - algoliasearch-jekyll

algolia:
  application_id: 'DK7WY1DV05'
  index_name: 'test_article'
  read_only_api_key: '2a1c4577ae9ca90f32d9a0f1c70b79c1'
  excluded_files:
    - 404.html
    - index.html

compress_html:
  clippings: all
