# Site settings
title: Jan Czizikow
description: This is the site of Jan Czizikow, a Web Developer. The site is just a list of things he's been up to including blog and projects.
baseurl: ""
url: "https://www.janczizikow.com"

# Social
socialimg: /img/social.jpg # 1200 x 630 pixels
facebook: johnny.czizikow
twitter: jan_czizikow
linkedin: janczizikow
behance: janczizikow
dribbble: janczizikow
github: janczizikow
googleplus: 106682453870996888295
instagram: shanlongjj

# Contact
phone: "(+86) 131-6700-7112"
email: "jan.czizikow@gmail.com"
location: Warsaw, Poland

#Others
markdown: kramdown
highlighter: rouge # or pygments or null
exclude: [README.md, assets/css/pages, "node_modules", "bower_components", Gemfile, "package.json", "bower.json", vendor]
include: ['_pages']
permalink: /:title/
# Gems
plugins:
  - jekyll-paginate

compress_html:
  clippings: all
