seo:
  rel-author: 'Jan Czizikow'
  rel-publisher: 'https://plus.google.com/u/0/106682453870996888295'

menu:
  - {name: 'About', link: '#about'}
  # - {name: 'Skills', link: '#skills'}
  - {name: 'Projects', link: '#projects'}
  - {name: 'Blog', link: '#blog'}
  - {name: 'Contact', link: '#contact'}

projects:
- {name: Blanccstate, cat: 'website', folder: 'blanccstate', file: 'projects/blanccstate.html'}
- {name: the clinic, cat: 'email', folder: 'the-clinic', file: 'projects/the-clinic.html'}
- {name: Minimal Portfolio, cat: 'website', folder: 'minimal-portfolio', file: 'projects/minimal-portfolio.html'}


#-------------------------------
# Hero Area Settings

tagline: >
  Just a simple dude who wants to build cool web experiences.

cta: >

#-------------------------------
# About Site Settings

about: >
  Previously UX Project manger at Motion Global - an e-commerce retailer of eyewear and contact lenses.
  Now, a self-starting developer seeking to launch a career building
  web applications and services. Familiar with development and
  deployment processes for many web-based technologies.
